create table public.products (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  name text not null,
  price numeric not null default '0'::numeric,
  quantity integer not null default 0,
  constraint products_pkey primary key (id)
) TABLESPACE pg_default;