CREATE TABLE public.order_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  order_id BIGINT NOT NULL,
  product_id BIGINT NOT NULL,
  total_quantity INTEGER NOT NULL DEFAULT 0,
  total_price NUMERIC NOT NULL DEFAULT '0'::NUMERIC,
  CONSTRAINT order_items_pkey PRIMARY KEY (id),
  CONSTRAINT order_items_product_id_fkey FOREIGN KEY (product_id) REFERENCES products (id),
  CONSTRAINT order_items_order_id_fkey FOREIGN KEY (order_id) REFERENCES orders (id)
) TABLESPACE pg_default;
