create table public.order_items (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  order_id bigint not null,
  product_id bigint not null,
  quantity integer not null default 0,
  total_price numeric not null default '0'::numeric,
  constraint order_items_pkey primary key (id),
  constraint order_items_product_id_fkey foreign KEY (product_id) references products (id),
  constraint order_items_order_id_fkey foreign KEY (order_id) references orders (id)
) TABLESPACE pg_default;