create type status_order as ENUM (
  'pending',
  'success',
  'failed'
);

create table public.orders (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  user_id uuid not null default auth.uid (),
  status status_order not null default 'pending',
  total_price numeric not null default '0'::numeric,
  constraint orders_pkey primary key (id),
  constraint orders_user_id_fkey foreign KEY (user_id) references auth.users (id)
) TABLESPACE pg_default;